# Generated by Django 2.1.5 on 2020-05-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadet_Has_Superior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDT_X_Num', models.CharField(max_length=6)),
                ('CDT_Sup_X_Num', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cadets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('X_Num', models.CharField(max_length=6)),
                ('Barracks_Name', models.CharField(max_length=20)),
                ('Room_Number', models.PositiveSmallIntegerField()),
                ('cadet_has_superior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Cadet_Has_Superior')),
            ],
        ),
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gig_Name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Pass', models.BooleanField()),
                ('Comments', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barracks_Name', models.CharField(max_length=100)),
                ('Room_Number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='inspections',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Rooms'),
        ),
        migrations.AddField(
            model_name='gigs',
            name='inspection',
            field=models.ManyToManyField(to='AMIApp.Inspections'),
        ),
        migrations.AddField(
            model_name='cadets',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Position'),
        ),
        migrations.AddField(
            model_name='cadets',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Rooms'),
        ),
    ]
