# Generated by Django 2.1.5 on 2020-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMIApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='Gig_Name',
            field=models.CharField(max_length=2000),
        ),
    ]
