# Generated by Django 2.1.5 on 2020-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMIApp', '0002_auto_20200504_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='inspection',
        ),
        migrations.AddField(
            model_name='inspections',
            name='gigs',
            field=models.ManyToManyField(to='AMIApp.Gigs'),
        ),
    ]
