# Generated by Django 2.1.5 on 2020-05-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMIApp', '0003_auto_20200504_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadets',
            name='cadet_has_superior',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Cadet_Has_Superior'),
        ),
        migrations.AlterField(
            model_name='cadets',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Rooms'),
        ),
    ]
