# Generated by Django 2.1.5 on 2020-05-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMIApp', '0004_auto_20200504_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadets',
            name='cadet_has_superior',
        ),
    ]
