# Generated by Django 2.1.5 on 2020-05-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMIApp', '0006_auto_20200504_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadets',
            name='Barracks_Name',
        ),
        migrations.RemoveField(
            model_name='cadets',
            name='Room_Number',
        ),
        migrations.AlterField(
            model_name='cadets',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Rooms'),
        ),
    ]
