# Generated by Django 2.1.5 on 2020-05-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMIApp', '0008_cadets_cadet_has_superior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadets',
            name='cadet_has_superior',
        ),
        migrations.AddField(
            model_name='cadets',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AMIApp.Cadets'),
        ),
        migrations.DeleteModel(
            name='Cadet_Has_Superior',
        ),
    ]
